blank_issues_enabled: false
contact_links:
  - name: GitHub Community Support
    url: https://github.community/
    about: Please ask and answer questions here.
  - name: Security Bug Bounty
    url: mailto:telefonica.fiware@gmail.com
    about: Please report security vulnerabilities here.
